version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    entrypoint: ["/bin/sh", "-c"]
    command: |
      "if ! ollama list | grep -q 'tinyllama'; then 
          echo 'Modello non trovato. Download in corso...'; 
          ollama pull tinyllama; 
       fi && 
       ollama serve"

volumes:
  ollama_data:
